export const projects = [
  {
    id: 1,
    name: "Next.js",
    description: "The React Framework for the Web. Used by some of the world's largest companies, Next.js enables you to create high-quality web applications by enabling React Server Components and dynamic routing.",
    domain: "Web Development",
    technologies: ["Next.js", "React", "TypeScript", "Webpack"],
    difficulty: "Intermediate",
    stars: 125000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/vercel/next.js",
    language: "TypeScript",
    issues: 1240,
    license: "MIT"
  },
  {
    id: 2,
    name: "React",
    description: "A declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called components.",
    domain: "Web Development",
    technologies: ["React", "JavaScript", "JSX", "HTML/CSS"],
    difficulty: "Advanced",
    stars: 224000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/facebook/react",
    language: "JavaScript",
    issues: 980,
    license: "MIT"
  },
  {
    id: 3,
    name: "VS Code",
    description: "Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. It features code completion, debugging, Git integration, and extensibility.",
    domain: "Web Development",
    technologies: ["TypeScript", "Electron", "Node.js", "HTML"],
    difficulty: "Advanced",
    stars: 165000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/microsoft/vscode",
    language: "TypeScript",
    issues: 4500,
    license: "MIT"
  },
  {
    id: 4,
    name: "PyTorch",
    description: "An open-source machine learning framework that accelerates the path from research prototyping to production deployment. PyTorch provides tensor computation with strong GPU acceleration.",
    domain: "AI/ML",
    technologies: ["Python", "C++", "CUDA", "NumPy"],
    difficulty: "Advanced",
    stars: 82000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/pytorch/pytorch",
    language: "Python",
    issues: 3200,
    license: "BSD 3-Clause"
  },
  {
    id: 5,
    name: "Fastify",
    description: "An efficient and low-overhead web framework for Node.js, designed to provide the best developer experience with minimal overhead and a powerful plugin architecture.",
    domain: "Backend",
    technologies: ["Node.js", "JavaScript", "Schema", "HTTP"],
    difficulty: "Beginner",
    stars: 31000,
    beginnerFriendly: true,
    githubUrl: "https://github.com/fastify/fastify",
    language: "JavaScript",
    issues: 45,
    license: "MIT"
  },
  {
    id: 6,
    name: "Svelte",
    description: "A radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step.",
    domain: "Web Development",
    technologies: ["Svelte", "HTML", "CSS", "Compiler"],
    difficulty: "Beginner",
    stars: 78000,
    beginnerFriendly: true,
    githubUrl: "https://github.com/sveltejs/svelte",
    language: "TypeScript",
    issues: 350,
    license: "MIT"
  },
  {
    id: 7,
    name: "Deno",
    description: "A simple, modern, and secure runtime for JavaScript, TypeScript, and WebAssembly that uses V8 and is built in Rust. It has built-in testing, linting, and formatting tools.",
    domain: "Backend",
    technologies: ["Rust", "TypeScript", "V8", "WebAssembly"],
    difficulty: "Intermediate",
    stars: 95000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/denoland/deno",
    language: "Rust",
    issues: 720,
    license: "MIT"
  },
  {
    id: 8,
    name: "Ansible",
    description: "A radically simple IT automation system that handles configuration management, application deployment, cloud provisioning, ad-hoc task execution, and multi-node orchestration.",
    domain: "DevOps",
    technologies: ["Python", "YAML", "Shell", "Linux"],
    difficulty: "Intermediate",
    stars: 61000,
    beginnerFriendly: true,
    githubUrl: "https://github.com/ansible/ansible",
    language: "Python",
    issues: 1800,
    license: "GPL-3.0"
  },
  {
    id: 9,
    name: "Docker Moby",
    description: "The Moby Project is an open-source project created by Docker to enable and accelerate software containerization. It provides a library of components, a framework, and reference designs.",
    domain: "DevOps",
    technologies: ["Go", "Containerd", "Linux", "OS"],
    difficulty: "Advanced",
    stars: 69000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/moby/moby",
    language: "Go",
    issues: 1100,
    license: "Apache-2.0"
  },
  {
    id: 10,
    name: "Tiptap",
    description: "A headless, extendable, and rich-text editor framework for React, Vue, and vanilla JavaScript. Build custom editors with full control over design and behavior.",
    domain: "Web Development",
    technologies: ["JavaScript", "ProseMirror", "Editor", "TypeScript"],
    difficulty: "Beginner",
    stars: 23000,
    beginnerFriendly: true,
    githubUrl: "https://github.com/ueberdosis/tiptap",
    language: "TypeScript",
    issues: 120,
    license: "MIT"
  },
  {
    id: 11,
    name: "React Native",
    description: "A framework for building native apps using React. React Native combines the best parts of native development with React, a best-in-class JavaScript library for building user interfaces.",
    domain: "Mobile Development",
    technologies: ["React Native", "JavaScript", "Objective-C", "Java", "iOS", "Android"],
    difficulty: "Intermediate",
    stars: 115000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/facebook/react-native",
    language: "JavaScript",
    issues: 1800,
    license: "MIT"
  },
  {
    id: 12,
    name: "Flutter",
    description: "Google's SDK for crafting beautiful, fast, user experiences for mobile, web, and desktop from a single codebase. Flutter works with existing code and is used by developers worldwide.",
    domain: "Mobile Development",
    technologies: ["Flutter", "Dart", "Skia", "C++", "Android", "iOS"],
    difficulty: "Beginner",
    stars: 160000,
    beginnerFriendly: true,
    githubUrl: "https://github.com/flutter/flutter",
    language: "Dart",
    issues: 5000,
    license: "BSD 3-Clause"
  },
  {
    id: 13,
    name: "SwiftLint",
    description: "A tool to enforce Swift style and conventions, loosely based on the now-archived GitHub Swift Style Guide. It helps maintain code-base cleanliness.",
    domain: "Mobile Development",
    technologies: ["Swift", "AST", "Linter", "iOS"],
    difficulty: "Beginner",
    stars: 17000,
    beginnerFriendly: true,
    githubUrl: "https://github.com/realm/SwiftLint",
    language: "Swift",
    issues: 240,
    license: "MIT"
  },
  {
    id: 14,
    name: "Rust",
    description: "A language empowering technology that empowers everyone to build reliable and efficient software. Rust is blazingly fast and memory-efficient, with no runtime or garbage collector.",
    domain: "Systems & Security",
    technologies: ["Rust", "Compiler", "LLVM", "Linker"],
    difficulty: "Advanced",
    stars: 98000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/rust-lang/rust",
    language: "Rust",
    issues: 9500,
    license: "MIT"
  },
  {
    id: 15,
    name: "HashiCorp Vault",
    description: "A tool for securely accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, and more. It provides unified encryption.",
    domain: "Systems & Security",
    technologies: ["Go", "Vault", "Cryptography", "Security"],
    difficulty: "Intermediate",
    stars: 28000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/hashicorp/vault",
    language: "Go",
    issues: 850,
    license: "BSL 1.1"
  },
  {
    id: 16,
    name: "eBPF Compiler Collection",
    description: "BCC is a toolkit for creating efficient kernel tracer and manipulation programs, and includes several useful tools and examples. It makes use of extended BPF (eBPF).",
    domain: "Systems & Security",
    technologies: ["C++", "Python", "eBPF", "Linux Kernel"],
    difficulty: "Advanced",
    stars: 19000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/iovisor/bcc",
    language: "C++",
    issues: 450,
    license: "Apache-2.0"
  },
  {
    id: 17,
    name: "Transformers",
    description: "State-of-the-art Machine Learning for PyTorch, TensorFlow, and JAX. Transformers provides APIs and tools to easily download and train state-of-the-art pretrained models.",
    domain: "AI/ML",
    technologies: ["Python", "PyTorch", "TensorFlow", "Transformers", "NLP"],
    difficulty: "Intermediate",
    stars: 130000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/huggingface/transformers",
    language: "Python",
    issues: 1200,
    license: "Apache-2.0"
  },
  {
    id: 18,
    name: "Kubernetes",
    description: "Production-grade container scheduling and management. Kubernetes is an open source system for automating deployment, scaling, and management of containerized applications.",
    domain: "DevOps",
    technologies: ["Go", "Kubernetes", "Docker", "Containers"],
    difficulty: "Advanced",
    stars: 105000,
    beginnerFriendly: false,
    githubUrl: "https://github.com/kubernetes/kubernetes",
    language: "Go",
    issues: 3400,
    license: "Apache-2.0"
  }
];

export function getProject(id) {
  const numericId = parseInt(id, 10);
  return projects.find((p) => p.id === numericId) || null;
}

export function formatStars(n) {
  if (n >= 1000) {
    return (n / 1000).toFixed(1).replace(/\.0$/, "") + "k";
  }
  return n.toString();
}
